name: Build docker image

on:
  push:
    branches:
      - main
    paths:
      - 'iac/*'
      - '.github/workflows/build-iac.yml'
  pull_request:
    paths:
      - 'iac/*'
      - '.github/workflows/build-iac.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  package:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/${{ github.repository }}/iac
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha,format=long

      - name: Build Docker Container
        uses: docker/build-push-action@v7
        with:
          context: ./iac
          target: iac
          platforms: "linux/amd64,linux/arm64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Docker meta (vault)
        id: meta-vault
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/${{ github.repository }}/iac
          flavor: |
            latest=auto
            prefix=
            suffix=-vault
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha,format=long

      - name: Build Docker Container (vault)
        uses: docker/build-push-action@v7
        with:
          context: ./iac
          target: iac-vault
          platforms: "linux/amd64,linux/arm64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-vault.outputs.tags }}
          labels: ${{ steps.meta-vault.outputs.labels }}
